In [1]:
import numpy as np

In [2]:
a = np.random.randn(3,3)
a

array([[-0.41526359,  0.89280007,  1.57318955],
       [-1.13613225,  0.7500599 ,  0.66465403],
       [-1.46764318,  0.63577848, -0.21866769]])

In [3]:
b  = np.random.randn(3,1)
b

array([[-0.7977691 ],
       [ 1.24379155],
       [-0.64953688]])

In [5]:
a*b

array([[ 0.33128446, -0.71224831, -1.25504201],
       [-1.41311169,  0.93291816,  0.82669107],
       [ 0.95328836, -0.41296157,  0.14203273]])

In [6]:
a = np.random.randn(4,3)
a

array([[-1.16295249, -0.31929337, -0.75609738],
       [ 0.59091843,  1.43123418,  0.1572994 ],
       [-0.69435252, -0.37726435, -0.7891793 ],
       [-1.39398923, -0.43437405, -1.38830668]])

In [7]:
b  = np.random.randn(3,2)
b

array([[ 0.17854939, -0.91527708],
       [ 1.80092012, -0.17446441],
       [-0.65281008,  0.25315002]])

In [8]:
a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 